### PR TITLE
JOSS submission

### PR DESCRIPTION
**Pull request by ndawe**
Preparing a root_numpy paper for submission to JOSS: http://joss.theoj.org/

TODO:

- [x] paper.md
- [x] Get new DOI for latest release

### CODE REVIEW

**Comment by kratsg** [comment]
Can you switch my email to kratsg@gmail.com?

**Comment by ndawe** [comment]
sure

**Comment by ndawe** [comment]
Comments on the latest draft?

https://www.dropbox.com/s/09p9ru6snmxv2jf/root_numpy.pdf?dl=0

**Comment by ndawe** [comment]
Keep in mind that JOSS papers are intended to be very brief (typically one page or less) so we don't need to justify or describe every detail.

**Comment by ndawe** [comment]
As described in their submission guidelines:

What should my paper contain?

JOSS papers should contain the following:

A list of the authors of the software
Author affiliations
A short summary describing the high-level functionality of the software
A list of key references including a link to the software archive

**Comment by ndawe** [comment]
>>> Please add a legend on both plots. If the plot on the right is cropped out, nobody knows which is ROOT and which is root_numpy.

While this may be common practice in ATLAS publications, I don't think we need to accommodate that here. I only show the legend in the left panel to avoid duplication and clutter. If by chance someone wants to show the right panel alone they can also copy/paste the legend onto the right plot.

>>> One needs to justify why the benchmarking makes sense. Why benchmark these two features? Do they seem related [one makes a plot, one makes an array]?

ttree.Draw() just fills a histogram or graph (I use the "goff" option to prevent any graphics rendering), also adding ">>hsqrt(1,0,1)" so the filling complexity is minimal changes nothing. I think Draw() is a pretty good benchmark since it is similar in complexity and familiar to users. I want this plot to basically suggest that you don't necessarily lose any speed by moving from a TTree::Draw()-based analysis to numpy arrays.

>>> ROOT format or TTree format? ROOT files can have lots of things, but root_numpy is probably geared towards files with TTrees.

ROOT format. But anyway I've removed this in the latest version.

>>> One might want to explain a little more about how root_numpy and ROOT interface, and how root_numpy and numpy interface.

I feel this goes beyond the level of detail required in the paper. The paper is really just meant to be a citable pointer to the documentation.

**Comment by ndawe** [comment]
I'll merge this now so I can begin the JOSS submission process.

**Pull request merged**
