### PR TITLE
Update to documentation and preparation towards the 4.8.0 release

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi, it's probably time to get a new release picking up all updates from the last year.

This PR bumps up the version number to 4.8.0 and update the doc where relevant.

**Comment by eduardo-rodrigues** [comment]
Thanks a lot for the merge, @kratsg. Will you tag and deploy the release?

**Comment by kratsg** [comment]
@piti118 or @ndawe -- can you give me access to push new releases to pypi? https://github.com/scikit-hep/root_numpy/releases/tag/4.8.0 to https://pypi.org/project/root_numpy/

**Comment by eduardo-rodrigues** [comment]
That reminds me: it would be ideal to also have somebody from the scikit-hep admins with the rights to push to PyPI :-).

**Comment by eduardo-rodrigues** [comment]
Hi @ndawe, @piti118, can one of you give @kratsg and I the right to push the new `root_numpy` release to PyPI? Nobody from the Scikit-HEP org can, and that's not good at all ;-).

Thanks a lot.

**Comment by ndawe** [comment]
Doing this now! I'll ping back shortly

**Comment by ndawe** [comment]
@eduardo-rodrigues and @kratsg, you're both now owners

**Comment by eduardo-rodrigues** [comment]
Brilliant, thanks a lot @ndawe!

@kratsg, will you push to PyPI or shall I?

**Comment by eduardo-rodrigues** [comment]
@kratsg, FYI I've just pushed to PyPI. Note that the automatic upload to Zenodo did not work out. for this tag 4.8.0. I will try and have a look.

**Comment by kratsg** [comment]
> @kratsg, FYI I've just pushed to PyPI. Note that the automatic upload to Zenodo did not work out. for this tag 4.8.0. I will try and have a look.

Thanks! I've been a bit busy unfortunately.

**Pull request merged**
